theme: jekyll-theme-slate
title: Data Driven Systems Medicine
email: datadrivensystemsmedicine@gmail.com
url: datadrivensystemsmedicine.github.io
description: "Data Driven Systems Medicine Workshop, hosted at Cardiff University from June 11-12th 2019."